---
title: KSE master thesis map
description: |
  Which topics are popular among KSE students?
author: Vadym Yudenko
date: 2023-07-14
draft: true 
categories:
  - KSE
  - thesis
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
# xaringanExtra::use_panelset()
```

```{r}
# library(rvest)
# library(httr)
# library(xml2)
# library(pdftools)
library(ggplot2)
library(tidyverse)
library(writexl)
library(readxl)
library(readr)
library(kableExtra)
library(DT)
library(lubridate)
library(extrafont)
library(tm)
library(stringr)
```



















```{r}
#code works, but pdfs are empty 
# 
# base_url <- "https://kse.ua/community/stories/"
#  
# # Define a custom function to construct the URL based on the year
# construct_url <- function(year) {
#    if (year == 2020) {
#      return(paste0(base_url, "magisterski-diplomni-proyekti-", year, "/"))
#    } else if (year == 2021) {
#      return(paste0(base_url, "magisterski-diplomni-proyekti-", year, "/"))
#    } else {
#      return(paste0(base_url, "ma-theses-", year, "/"))
#    }
#  }
#  
# for(year in 1998:2020) {
#     url <- construct_url(year)
#     webpage <- read_html(url)
#     pdf_links <- webpage %>% html_nodes("a[href$='.pdf']") %>% html_attr("href")
# 
#     for(link in pdf_links) {
#         response <- GET(link, write_disk(paste0(year, "-", basename(link)), overwrite = TRUE))
# 
#         if(http_status(response)$category != "Success") {
#             warning(paste("Failed to download", link, "with status", http_status(response)$message))
#         }
#     }
# }

```

Check if 2020 downloaded fully - there are issues
