---
title: North Eastиний
description: |
  Remembering Amstor Mall Airstrike
author: Vadym Yudenko
date: 2022-07-28
draft: true
tags: 
  - War
  - Experiences
---




По мінному полю я йшов й озирався
а потім побачив тебе
тебе у посадці
я враз закохався
й мені усміхнулись з небес.
Мені захотілось
ось тут окопатись
поруч з твоїм бліндажем 
я маю маленьку піхотну лопатку
вона мене береже.
Хочеш
я твоїм броником буду 
в нім заховаєшся
як в халабуді?
Буду з тобою
завжди на війні
лиш броником бути дозволь ти мені.
Одягнеш
накинеш
поверх ерпеески
стріляють та я захищу
я буду співати тобі колискову
сховаю від мін і дощу.
І всі твої сни я буду тримати
гарячі, як зброя в бою
і небо схоплю, червоне томатне
додолу його розіллю.
Хочеш
я твоїм броником буду?
—
Люди
як бмп
їдуть вперед
поміж посадки й ліси
і поки не випаде дощ
доїдуть до вулиць і площ.
Люди
як бмп
стріляють в ворожу посадку
у темряву і порожнечу
допоки ворог впаде
люди 
як бмп.
___
Підірватись на землі
пефеемка, пемеемка 
і летіти в небеса
ніхто і не побачить.
__
Перестаньте флудити по радіо
говоріть лиш по справі по радіо
ооо.
—
Ти вийшла заміж за зиму
ти вийшла заміж за зиму
мені лишила сосни
збудую з них бліндаж я.
Спартан женеться по шосе
і він кудись мене несе
де я не був ще досі
лишив бліндаж із сосен.
Кулі - колишуться за вікном
окопи - фортеця моя й стіна
кулі лякають своїм теплом
сосни хороше перекриття.
Стріляю це мої слова
копаю це мої слова
дивлюся в тепловізор
чи пак ніхто не лізе.
Дтина бавилась в пісок
дитина бігла на урок
вони розбили школу
туди ніхто не ходить.
Кулі - колишуться за вікном
окопи - фортеця моя й стіна
кулі лякають своїм теплом
сосни хороше перекриття.
Ти вийшла заміж за зиму
ти вийшла заміж за зиму
мені лишила сосни
десь заховалась осінь.
__
В ворожім лісі так багато сторін
в яку ж із них поцілить?
У хлопців моїх всього декілька мін
що полетять курсивом
і це мабуть красиво.
Когось це має вбити.

Кривцов Максим