---
title: Hospitalier 
description: |
  NAEMT ASM Training
author: Vadym Yudenko
date: 2022-07-28
format: html
draft: true
editor: source
categories: 
  - War
  - Experiences
---

## 

I am no soldier. The closest I came to military warfare was playing (ru: войнушки). Sticks

## Taxonomy of sticks

The choice of armament was limited to what we had at hand. And there were a lot of sticks.

The sticks varied in shapes and sizes. Of course, the stick must have had to resemble a gun to qualify. But depending on your imagination, every stick could be a gun.

Ideal stick had a good handle and a long straight barrel. Some bump to serve as a trigger or a bump to serve as a sight was a plus, but those were rare.

A small stick with a good handle and a small straight barrel was a pistol. While there were many pistols, guys rarely used them, as there were more fun sticks to play with. For example, a stick with a curvy barrel and a bump to serve as a scope. This type of stick looked more menacing and was way cooler to carry around with. This was a machine gun. One day there was a storm and one tree fell and broke into two pieces - that day we added a thick branch to our arsenal. This was a bazooka (ru: базука).

In addition to sticks we used small stones, chestnuts and dust bombs to overpower our enemy. We would fill the plastic bags (целофоновые пакетики) with a ordinary dust, tie it and there you had a grenade. Sometimes they didn't break on fall, another time you clip the bag with your finger and as you swing it rips and spills the contents on the unfortunate kid.

For all you know your enemy could've already called home for dinner and you're there.

The point was not to win or hurt, we did it for the thrill of it.

## Ukraine Legion

Recently our government has made it clear that more people will be mobilized \[source\]

People are preparing to fight. [Ukrainian Legion](https://www.frontliner.com.ua/ukrainian-legion-training/).

## 202...

We do find ourselves in a zugzwang.

Not everyone wants to fight in the army. Those who wanted already have. Those who haven't are either unable or, which is more likely, unwilling.

One must prepare for the worst. In the peacetime it is advised people learn to provide basic medical help. This is even more important in wartime. Learning to work with weapons and learn Ukrainian (yes!)
