---
title: "Why track your daily life?"
description: |
  Thinking about tracking your daily life and most importantly, why would you do that.
  Timetracking part 2 of N
author: 
 - name: Vadym Yudenko
   affiliation: American University Kyiv
   affiliation-url: https://auk.edu.ua/en/
date: 2023-07-14
draft: true 
categories:
  - timetracking
  - self-surveillance
---

## Why would you want to track your daily life?


- who will benefit and in what way from spending some time during the day tracking how they have spent their time
- time management skill
- good reflection practice
- 


## My story 

- Why have I started tracking my daily life
- 

## Introduction (why have I started tracking my time?)


Sometime in Summer 2019 I was bored and wasted days doing a whole lot of nothing. Before I never knew one can get tired from doing nothing, but that summer I languished a lot.

On one such morning, having woken up at 12am hopelessly fatigue I had enough. I hated myself, for I was doing a whole lot of nothing, and at around that time I realized I needed meaning in my life - feeling of accomplishment and being proud of myself; was reading motivational books like 7 Habits and thinking about what do I do with my life. This is the WHY, now about the HOW.

Earlier, in winter 2019 I started low-key learning Japanese on Duolingo, Drops, you name it. Overtime I got exposure to some real-deal try-hard stuff: Anki-gang, AJATT/MIA/Migaku. Guys were hell bent of mastering the language, they would spend days with the language, cut their social ties with external world - I liked them. Their approach - spend as much time with the language seamed reasonable, after all this IS how you acquire language. Among some of the stuff the One of them shared a video of how he was tracking his Japanese learning journey. Stars aligned and I started tracking my time.


### Importance of balance

- 

### Food for thought

- taking a break 
- being more mindful
- 





Unanswered questions

Eventually I have got my data-driven evidence-based answer as to...

```{r}
# circle_plot <-
#   data_long |>
#   filter(activity == "Waste") |>
#   count(day, hour) |>
#   mutate(
#     hour_label = case_when(
#       hour == 12 ~ "12pm",
#       hour == 0 ~ "12am",
#       hour > 12 ~ paste0(hour - 12, "pm"),
#       hour < 12 ~ paste0(hour, "am")
#     ),
#     pct = n / sum(n)
#     )
# 
# 
# tooltip_hour <- function(day, hour_label, ...) {
#   this_hour_count <-
#     circle_plot |>
#     filter(hour_label == !!hour_label)
# 
#   this_hour_total <- sum(this_hour_count$n)
#   this_hour_pct <- scales::percent(this_hour_total / sum(circle_plot$n), 0.1)
#   this_hour_total <- trimws(format(this_hour_total, big.mark = ","))
# 
#   this_hour_days <-
#     this_hour_count |>
#     mutate(
#       across(pct, scales::percent_format(0.1)),
#       across(n, format, big.mark = ","),
#       across(n, trimws),
#       text = glue("{day}: {pct} ({n})"),
#       text = if_else(day == !!day, glue("<strong>{text}</strong>"), text)
#     ) |>
#     glue_data("<li>{text}</li>") |>
#     glue_collapse()
# 
#   glue::glue(
#     "<p><strong>{hour_label}</strong><br><small>{this_hour_pct} of total ({this_hour_total})</small></p>",
#     "<ul>{this_hour_days}</ul>"
#   )
# }
# 
# circle_plot$tooltip <- pmap_chr(circle_plot, tooltip_hour)
# 
# 
# plot_time_of_day <-
#   ggplot(circle_plot) +
#   aes(y = n, fill = day, x = hour, data_id = hour, tooltip = tooltip) +
#   geom_area(
#     data = function(d) {
#       # Shade from midnight-6am and 6pm-midnight, kinda like geom_step_area()
#       max_count <- max(d$n)
#       tibble(
#         day = sort(rep(unique(d$day), 6)),
#         # hour = rep(c(0, 6, 6.01, 18, 18.01, 24), 7),
#         hour = rep(c(6, 12, 12.01, 6, 6.01, 12), 7),
#         n = rep(c(max_count, max_count, 0, 0, max_count, max_count), 7),
#         tooltip = ""
#       )
#     },
#     fill = "#aaaaaa30",
#   ) +
#   ggiraph::geom_col_interactive(show.legend = FALSE, width = 1) +
#   facet_wrap(vars(day), nrow = 2) +
#   coord_polar(start = pi) +
#   scale_x_continuous(
#     breaks = seq(0, 23, 3),
#     minor_breaks = 0:23,
#     labels = c("12am", paste0(seq(3, 9, 3), "am"), "12pm", paste0(seq(3, 9, 3), "pm")),
#     limits = c(0, 24),
#     expand = expansion()
#   ) +
#   scale_y_continuous(expand = expansion(), breaks = seq(0, 100, 25)) +
#   scale_fill_discrete() +
#   labs(
#     title = "Did I really waste more time in the morning??",
#     x = NULL,
#     y = NULL
#   ) +
# #  theme_classic() +
#   theme(
#     axis.text.y = element_blank(),
#     axis.text.x = element_text(size = 10),
#     panel.grid.major.y = element_blank()
#   )
# 
# ggiraph::girafe(
#   ggobj = plot_time_of_day,
#   width_svg = 12,
#   height_svg = 8,
#   options = list(
#     ggiraph::opts_hover_inv("filter: saturate(30%) brightness(125%)"),
#     ggiraph::opts_hover(css = "opacity:1"),
#     ggiraph::opts_tooltip(
#       placement = "container",
#       css = "width: 12rem; font-family: var(--font-monospace, 'IBM Plex Mono');",
#       # These don't matter, position is set by CSS rules below
#       offx = 1000,
#       offy = 400,
#       use_cursor_pos = FALSE
#     )
#   ),
#   desc = knitr::opts_current$get("fig.alt")
# )
```

Code taken and adapted from Garrick Aden's blog

It depended on the day
