---
title: Making blood donations default
author: Vadym Yudenko
date: 2022-07-28
draft: true
categories: 
  - War
  - Experiences
---

Як стимулювати людей здавати кров?

Під час війни здача крові – це питання життя та смерті. У мирний час мало хто усвідослює про її важливість.  І хоч під час війни к-ть донорів збільшилась, цієї к-ть всеодно недостатньо щоб забезпечити навіть 2/3 пацієнтів. 
Причини чому люди не здають кров варіюються від наявності протипоказань до нестачі часу, та загалом для більшості здача крові стає проблемою, тільки коли вона потрібна людині або її близьким. Як каже Ірина Славінська, співзасновниця ДонорУА: «В Україні разове (або стихійне) донорство – все ще поширене явище. В разі гострої потреби донорами крові для пацієнта стають його друзі чи члени сім’ї, або ж донора шукають серед знайомих чи через соцмережі. Пошуками у такому разі родина пацієнта займається самостійно». До того ж люди можуть мати викривлене розуміння процедури чи просто боятись лікарів, голки, чіпування. 
Боротись проти цих упереджень та допомагати людять бути більш свідомими та здавати кров є критично важливим, щоб рятувати життя. Найпростіший варіант – займатись просвітництвом у школі, на роботі, просто на вулиці розвішуючи плакати. Це важлива робота, але є й інші способи впливу як наприклад запропонувати гроші. Знаючи про важливість не гарантує, що людина це зробить. Гроші можуть компенсувати втрати часу та змотивувати ту частину людей на яких звичайне просвітництво не діє. Але є ризик, що запроводження плати за здачу крові зменшить к-ть людей які здаватимуть кров – так званий «crowding out effect». Більшість людей хочуть допомогти, керуються альтруїстичними мотивами. Гроші повністю нівелюють будь-які альтруїстичні мотиви – тепер ти не донатиш тому що ти добрий, а тому що треба гроші. До того ж «люди, які отримують винагороду за кровоздачу, схильні до замовчування факторів, котрі можуть нашкодити реципієнту», - І. Славінська. 
Альтенативою до грошових є… негрошові. Це можуть бути заклики від opinion leaders до своїх аудиторії, знижки для тих, повідомлення про врятоване життя (сорс), хто здав кров, та інші бонуси (поділиться іншими варіантами у коментарях). 
Групові здачі крові, наприклад, вже не похід у лікарню, а зустріч з друзями. Отримавши цукерку після процедури, ми, як слухняні собаки Павлова, отримуємо пизитивну афірмацію, що ми зробили щось добре. Отримавши повідомлення про врятоване життя, навіть якщо це не так, makes us feel good about ourselves. І саме на це повинні бути спрямовані наші зусилля. Нам треба відчувати що ми робимо щось добре та схвалення інших. Малі зміни можуть не мати вплив на конкретного індивіда, але матимуть вплив на суспільство загалом. Роблячи здачу крові чимось звичайним, що не потребує зайвих зусиль та схвалюючи донорів ми створимо системне донорство, що рятуватиме нас і вас.

Де можна здати кров?
https://www.donor.ua/centers



Post:
В продовження попереднього посту про донорство крові (лінк) ми вирішили розглянути ще одне потенційне рішення низької залученості українців до донорства – зробити його дефолтним. А саме нас цікавить чи збільшиться к-ть донорів крові якщо гіпотетично впровадити default enrollment?
Ідея дефолту полягає у тому, що людям зазвичай важко або лінь обирати серед можливих опцій, і тому вони обирають дефолтну (базову) опцію. Дефолти спрощують нам життя і дуже часто ми навіть не звертаємо на них увагу. Ефект дефолту настільки сильний, що Google щороку сплачує більш ніж 26 мільярдів $$$ Apple, Samsung та іншим, щоб бути дефолтним браузером. «Це настільки велика сума, що McDonald’s заробляє менше продаючи бургери». Якщо людина хоче змінити браузер вона, звичайно, може, але дуже малий відсоток це роблять. As long as the person doesn’t view default as an intrusion, manipulation and is happy to play along, everyone is happy. 
Цю ідею почали використовувати в усіхсферах нашого життя, в тому числі і медицині. With organ donations, default options have been shown to increase the number of organ donors (але є винятки). These options don’t require an active decision – surgeons just do their own job. Unless the person or their family are opposed to the idea and decide to opt out, their organ(-s) will be given to the person in need. Defaults also have been used with vaccinations from flu, але не з донорством крові. І наскільки нам відомо, то ніхто ще не намагався впровадити таку систему. 
Уявімо пацієнта, якому необхідна терміново необхідне переливання крові. Їй можна взяти у 3 видів донорів: сім’я, за гроші, та на волонтерських засадах. Родичі можуть не бути поряд та бути не готовими здати кров через протипоказання, до того ж їх к-ть мала, порівняно з населенням. Можна придбати кров у оплачуваних донорів, що дорого та не гарантує якість та безпечність зданої крові (див. попередній пост). І останній варіант – це кров VNRBD неоплачувана кров донора здана на волонтерських засадах. З цих типів набільше можна розширити к-ть донорів які безоплатно здають кров. 
Зараз діє система що ті хто хочуть стати донором повинні explicitly agree (opt-in) щоб стати донором, таким чином тільки вмотивовані, свідомі люди, які готові витратити свій час та підготуватись стануть донорами. Якщо усіх, хто не має хронічних протипоказань, зареєструвати на здачу крові, наприклад, під час прийому до терапевта, терапевт повідомляє, що записав пацієнта в тому числі і на донорство. Ті хто не хочуть зможуть легко explicitly disagree (opt-out).  
Варто зазначити, що having people face consequences for failure to show up or be prepared for donation is an infringement on their rights. І можна очікувати негативної реакції від людей, що їх записали проти їх відома і ставлять перед фактом. До того ж у людей є свої плани та здача крові потребує певної підготовки, назначити певний час чи день може і буде зазвичай накладатися з планами. Є ті, кому байдуже і вони просто проігнорують чи прийдуть але непідготовленими (вживали алкголь, курили), що також нестиме ризик тим кому дістанеться кров, так і цим горе-донорам. 
Ідея дефолтого донорства крові є цікавою, але її реалізація, за чинного законодавста, є незаконною, тому що default enrollment може розгядатись як примус і ніхто не може бути змушений бути донором проти своєї волі. Але навіть якби ми могли впровадити таку програму, то є низка причин сумніватися в її успішності:
1.	Status quo (reversed): хоч людина і автоматично записана як потенційний донор, це не гарантуватиме її кооперацію. Їй всеодно необхідно докласти зусиль – виділити час, підготуватись. 
2.	Знецінення донорства: для багатьох донорство крові є благородним та важливим заняттям, намагаючись зробити його звичним явищем ми ризикуємо втратити людей, для яких донорство було місією.
3.	Податок на ЗОЖ: тільки ті хто піклуються про своє здоров’я найбільше «постраждають» від цього нововведення. 
Порівнюючи донорство крові та органів, то можна сказати, що «Dying is easy, blood donation isn’t». It requires more effort from the person in question and increases the risks and potential for error for everyone involved. It asks too much and can be viewed as an intrusion on our liberties. Not only this but it can be an ineffective strategy, as many people might come unprepared (having forgotten that they have smoked recently), and their visit will result into not usable blood, patients time and blood wasted. 
Дефолти, як і інші інструменти впливу на людську поведінку, не працюють однаково у різних контекстах. Що працює для вакцинації, може не спрацювати, у дуже схожій за механікою процедурі, у здачі крові. 




