---
title: "QALMRI"
description: |
  How to read an article 
author: 
 - name: Vadym Yudenko
   affiliation: American University Kyiv
   affiliation-url: https://auk.edu.ua/en/
date: 2023-12-07
toc-depth: 3
categories:
  - Reading
  - Research Methods
---

When you have found an interesting article. How do you read it? Do you try to understand every word and sentence? The language used in academic writing is often very complex and jargon-heavy! Not only do you want to read it, you want to understand and do something with the results, methodology, and conclusions. Either to guide your further search, or to use it in your own research. Being able to succinctly summarize an article is thus a very important skill.

QALMRI stands for ***Question***, ***Alternatives***, ***Logic***, ***Method***, ***Results***, and ***Inference***.

## Question

-   What are the questions the author is trying to answer?
-   What is the main point of the article?

> Questions may be specific or broad. Broad questions are typically too general to be answered by any single experiment and provide an overview of the general topic of interest (e.g., "What is the influence of playing video games on our daily behavior?"). Specific questions, on the other hand, can be addressed by a single experiment or set of experiments (e.g., "Does playing violent video games cause children to engage in more violent behavior?"). Answering one or more specific questions should be considered steps made toward addressing a broad question.
>
> [*Nicholaus Brosowsky and Olga Parshina*](https://attentionandlearninglab.com/papers/2017_BrosowskyParshina.pdf)

## Alternatives

-   What is the main hypotheses?
-   What alternative hypothesis can you think about?

## Logic

Logic is the the general idea of how alternatives will be differentiated. "If hypothesis 1 is true, then something-something...", "If hypothesis 2 is true, then something-something and something-something-else..."

## Methods

-   What is the study design?
-   What are the variables?
-   What is the procedure?

## Results

-   What are the most important results? 
-   Are they what you expected?

## Inference

-   What do authors conclude?
-   Are results consistent with the hypothesis?
-   What questions are left unanswered? 
-   What are the implications of the results? 
-   What are the limitations of the study?

|||
|---|---|
|**QALMRI**|**Where to find**|
|Question|Abstract, Introduction|
|Alternatives|Abstract, Introduction|
|Logic|Introduction, Methodology|
|Method|Methodology|
|Results|Results|
|Inference|Discussion|

## Sources

1.    [CrumpLab's Research Methods Lab](https://www.crumplab.com/ResearchMethodsLab/qalmri.html)
2.    [Learning To Read Scientific Journal Articles](https://bartlettje.github.io/pdfs/2021-10-06-learning-to-read-scientific-journal-articles.pdf)
3.    Brosowsky, N.P., Parshina, O., Locicero, A., & Crump, M.J.C. (2020, June 1), Teaching undergraduate students to read empirical articles: An evaluation and revision of the QALMRI method. https://doi.org/10.31234/osf.io/p39sc.

## Further reading

1. [How to read and understand a scientific paper: a guide for non-scientists](https://blogs.lse.ac.uk/impactofsocialsciences/2016/05/09/how-to-read-and-understand-a-scientific-paper-a-guide-for-non-scientists/)
2. [How to read a paper](https://web.stanford.edu/class/ee384m/Handouts/HowtoReadPaper.pdf)
3. [How to (seriously) read a scientific paper](https://www.science.org/content/article/how-seriously-read-scientific-paper)
4. [Synthesizing different bodies of work in your literature review: The Conceptual Synthesis Excel Dump (CSED) technique](http://www.raulpacheco.org/2016/06/synthesizing-different-bodies-of-work-in-your-literature-review-the-conceptual-synthesis-excel-dump-technique/)


