---
title: "100 stories"
description: |
  dating
author: 
 - name: Vadym Yudenko
   affiliation: American University Kyiv
   affiliation-url: https://auk.edu.ua/en/
date: 2023-07-14
draft: true 
categories:
  - dating
  - data
---



100 stories to 



When it comes to dating, I suck. I don't buy premium and I am not super popular. 
Like many of you I have tried using it countless time without any effect - matches are rare and you hate yourself everytime you spend 30 mins swiping left and right. 

This summer I have again came back to a dating scene after a 2 year hiatus - and it sucked. Writing cheesy pick up lines is playing into girls hands, as it seemed to me they all want to be entertained and tell their friends about this idiot who wrote them some stupid joke. 

After trying it my own way - I realized that even the process is meaningless - I am literally wasting my time. And then I had an idea.



I love telling stories and I love writing. 

Instead of writing puns, "Hey! Wanna go on a date?" I wrote stories! 


Dating should be fun! And if She picks up on it, than maybe we have a chance at something that will outlast both of us - loving relationship.


<aside>As you may have understood the author isn't into FWB, ONS and is looking only for serious relationship.<\aside>

# Stories highlights:
















