---
title: "How to Track one's life."
description: |
  Creating a workflow for seamless, effortless collection and visualization of daily activities.
  Timetracking part 3 of N
author: 
 - name: Vadym Yudenko
   affiliation: American University Kyiv
   affiliation-url: https://auk.edu.ua/en/
date: 2023-07-14
draft: true 
categories:
  - timetracking
  - self-surveillance
---




## Methodology (how have I approached this)

## Categorizing my life.

This goes along with my thinking about my life as multiple spheres. In order to lead a fulfilling, meaningful and balanced life I have to be successful in multiple of these spheres. 

[Read about it in my article]

Myself, a student at the time, had not much going in my life, except for Uni, Japanese and Sports. 

Initial categories: Study, Japanese, Reading, Sleep, Sports, Food, Transport, Friends and Family, Miscellaneous, Waste of Time.


Main categories:

Friends and Family: any interaction with friends and family (I later marked any interaction with human being as this :) )
Japanese: listening, writing, speaking, reading, thinking... all things Japanese
Study: 

Other:

Sleep includes night sleep, occasional naps and rests.

Reading: non-Japanese, non-Study reading 

Food: how often and when do I eat

Transport is self-explanatory: metro, bus, train, car, plain...

Miscellaneous is everything that doesn't fit into the above categories. It is not, unproductive time, per se, but it isn't something I should minimize. This category includes household chores, doctor visits, haircuts, shopping, some other 'i have to do this thing'.

Waste of Time: unproductive time. 'I wish I hadn't spend this time in this way...' 



I have created an Google Sheets file with

## setting up Excel sheet

Now that we have categories and hopefully things we want to track in hours. We can proceed to setting up tracking.

I have opted for Excel, because because!

(note): However there are other alternatives, which you might want to check out. 

Rows - Time; Cols - Days

The choice of time intervals of 20 mins was because at the time it seemed to strike a balance between precision and ease of tracking. If you want to be less precise than you can easily increase this time to 30, however, increasing to more than 30 mins is not a good idea, since all the precision is lost. 

One thing this workflow should achieve is be easy to use. 

Manually typing each cell is burdensome, instead we can create a dropdown list and we will have to click and choose the appropriate type. 

Sleep and recurring events can be mapped beforehand. 






## Tracking time 


## Problems



## Results

plots with commentary




## Thoughts and suggestions for wannabe time trackers

