---
title: North Eastиний
description: |
  Remembering Amstor Mall Airstrike
author: Vadym Yudenko
date: 2022-07-28
draft: true
tags: 
  - War
  - Experiences
---

https://en.wikipedia.org/wiki/True_north

$$Д=(В*1000)/У$$

2.  Формули тисячної та їхнє практичне застосування Залежно від кута, дуга якого дорівнює 1/6000 кола, й радіуса (відстані), одній тисячній кута в декілька тисячних відповідає довжина дуги В, що дорівнює одній тисячній дальності (1/1000), помноженій на кут, що містить У тисячних, можна визначити лінійну величину будь-якого центрального кута, якщо відома його кутова величина і відстань В = д × у/1000, звідси Д = В × 1000/У, та У = В × 1000/Д. Отримані формули звуться формулами тисячної та знаходять широке застосування в стрілецькій практиці. У цих формулах: Д --- (R --- радіус кола) --- відстань до предмета в метрах; У --- кут, під яким видно предмет у тисячних, чи кутова величина між точками в поділках кутоміра. Наприклад, 0-17, у формулу підставляється 17; 1-25 --- ця формула записується 125; В --- висота (ширина, довжина) предмета, тобто довжина хорди (дуги) АС. Для запам'ятовування формул можна користуватися таким способом, записаним у два рядки: (д × у)/(В × 1000), (образно ДУй в 1000).
