---
title: "christopher_hitchens"
description: |
  A short description of the post.
author: Vadym Yudneko
date: 2023-08-02
format: html
categories:
  - text
  - data
draft: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

SOURCE: <https://www.tidytextmining.com/sentiment.html>

```{r}
# library(tidytext)
# 
# get_sentiments("afinn")
# get_sentiments("bing")
# get_sentiments("nrc")
```

```{r}
# library(janeaustenr)
# library(dplyr)
# library(stringr)
# 
# tidy_books <- austen_books() %>%
#   group_by(book) %>%
#   mutate(
#     linenumber = row_number(),
#     chapter = cumsum(str_detect(text, 
#                                 regex("^chapter [\\divxlc]", 
#                                       ignore_case = TRUE)))) %>%
#   ungroup() %>%
#   unnest_tokens(word, text)
```

```{r}
# nrc_joy <- get_sentiments("nrc") %>% 
#   filter(sentiment == "joy")
# 
# tidy_books %>%
#   filter(book == "Emma") %>%
#   inner_join(nrc_joy) %>%
#   count(word, sort = TRUE)
```

```{r}
# library(tidyr)
# 
# jane_austen_sentiment <- tidy_books %>%
#   inner_join(get_sentiments("bing")) %>%
#   count(book, index = linenumber %/% 80, sentiment) %>%
#   pivot_wider(names_from = sentiment, values_from = n, values_fill = 0) %>% 
#   mutate(sentiment = positive - negative)
```

```{r}
# ggplot(jane_austen_sentiment, aes(index, sentiment, fill = book)) +
#   geom_col(show.legend = FALSE) +
#   facet_wrap(~book, ncol = 2, scales = "free_x")
```
